import { StyleSheet } from "@react-pdf/renderer";

export const COULEURS_RESULTAT_PDF = {
  noir: "#111111",
  gris: "#555555",
  bleu: "#1a4d7c",
  bleuContour: "#7eb6e0",
  bandeauTitre: "#d2dce6",
  bordureTableau: "#c8d2e6",
};

/** Hauteur commune avatar / QR dans le bandeau patient. */
export const TAILLE_BANDEAU_LATERAL_PDF = 72;

export const stylesResultatPdf = StyleSheet.create({
  page: {
    fontFamily: "Roboto",
    fontSize: 10,
    paddingTop: 200,
    paddingHorizontal: 42,
    paddingBottom: 48,
    color: COULEURS_RESULTAT_PDF.noir,
    backgroundColor: "#ffffff",
  },
  pageAnnexe: {
    fontFamily: "Roboto",
    fontSize: 10,
    paddingTop: 28,
    paddingHorizontal: 42,
    paddingBottom: 48,
    color: COULEURS_RESULTAT_PDF.noir,
    backgroundColor: "#ffffff",
  },
  enteteFixe: {
    position: "absolute",
    top: 28,
    left: 42,
    right: 42,
  },
  bandeauPatient: {
    borderWidth: 1,
    borderColor: COULEURS_RESULTAT_PDF.noir,
    padding: 8,
    marginBottom: 8,
    minHeight: 96,
    flexDirection: "row",
    alignItems: "center",
  },
  bandeauAvatarWrap: {
    width: TAILLE_BANDEAU_LATERAL_PDF,
    height: TAILLE_BANDEAU_LATERAL_PDF,
    marginRight: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  bandeauAvatar: {
    width: TAILLE_BANDEAU_LATERAL_PDF,
    height: TAILLE_BANDEAU_LATERAL_PDF,
    objectFit: "contain",
  },
  bandeauContenu: {
    flex: 1,
    paddingRight: 6,
    minWidth: 0,
  },
  bandeauQrWrap: {
    width: TAILLE_BANDEAU_LATERAL_PDF + 4,
    height: TAILLE_BANDEAU_LATERAL_PDF,
    alignItems: "center",
    justifyContent: "center",
  },
  bandeauQr: {
    width: TAILLE_BANDEAU_LATERAL_PDF,
    height: TAILLE_BANDEAU_LATERAL_PDF,
    objectFit: "contain",
  },
  bandeauLigne: {
    flexDirection: "row",
    marginBottom: 3,
  },
  bandeauCol: {
    width: "50%",
    flexDirection: "row",
    fontSize: 8.5,
    paddingRight: 4,
  },
  bandeauLabel: {
    fontWeight: "bold",
    width: 76,
    textTransform: "uppercase",
  },
  bandeauValeur: {
    flex: 1,
    minWidth: 0,
  },
  bandeauAdresseLigne: {
    flexDirection: "row",
    marginTop: 2,
    fontSize: 8.5,
  },
  bandeauAdresseValeur: {
    flex: 1,
    minWidth: 0,
    lineHeight: 1.25,
    fontSize: 8,
  },
  bandeauTitreExamen: {
    backgroundColor: COULEURS_RESULTAT_PDF.bandeauTitre,
    paddingVertical: 6,
    paddingHorizontal: 8,
    marginBottom: 4,
    marginTop: 4,
  },
  bandeauTitreTexte: {
    fontSize: 12,
    fontWeight: "bold",
    textAlign: "center",
    textTransform: "uppercase",
  },
  table: {
    borderWidth: 1,
    borderColor: COULEURS_RESULTAT_PDF.bordureTableau,
    marginBottom: 6,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#ffffff",
    borderBottomWidth: 1,
    borderBottomColor: COULEURS_RESULTAT_PDF.bordureTableau,
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: COULEURS_RESULTAT_PDF.bordureTableau,
  },
  cellHeader: {
    paddingVertical: 4,
    paddingHorizontal: 3,
    fontSize: 9,
    fontWeight: "bold",
    textAlign: "center",
    borderRightWidth: 1,
    borderRightColor: COULEURS_RESULTAT_PDF.bordureTableau,
  },
  cell: {
    paddingVertical: 3,
    paddingHorizontal: 3,
    fontSize: 9,
    borderRightWidth: 1,
    borderRightColor: COULEURS_RESULTAT_PDF.bordureTableau,
  },
  cellCenter: { textAlign: "center" },
  cellLast: { borderRightWidth: 0 },
  sectionTitre: {
    fontSize: 10,
    fontWeight: "bold",
    textAlign: "center",
    marginTop: 6,
    marginBottom: 4,
  },
  sectionTexte: {
    fontSize: 9,
    lineHeight: 1.35,
    marginBottom: 4,
  },
  commentaireLigne: {
    fontSize: 8,
    color: COULEURS_RESULTAT_PDF.gris,
    marginBottom: 2,
    paddingLeft: 4,
  },
  validationTitre: {
    fontSize: 10,
    fontWeight: "bold",
    marginTop: 10,
    marginBottom: 4,
  },
  validationBloc: {
    marginTop: 8,
    width: "100%",
  },
  validationLigne: {
    flexDirection: "row",
    fontSize: 9,
    marginBottom: 4,
  },
  signatureImage: {
    width: 110,
    height: 36,
    objectFit: "contain",
    marginVertical: 4,
  },
  validationFin: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
    width: "100%",
  },
  validationFinTrait: {
    flex: 1,
    borderBottomWidth: 1,
    borderBottomColor: COULEURS_RESULTAT_PDF.noir,
    height: 1,
  },
  validationFinCentre: {
    paddingHorizontal: 10,
    textAlign: "center",
    fontWeight: "bold",
    fontSize: 9,
  },
  annexeNomFichier: {
    fontSize: 9,
    color: COULEURS_RESULTAT_PDF.gris,
    marginBottom: 6,
    textAlign: "center",
  },
  annexeImageWrap: {
    alignItems: "center",
    marginTop: 4,
  },
  annexeImage: {
    maxWidth: "92%",
    maxHeight: 620,
    objectFit: "contain",
  },
  annexeErreur: {
    fontSize: 9,
    color: COULEURS_RESULTAT_PDF.gris,
    marginTop: 8,
    textAlign: "center",
    lineHeight: 1.35,
  },
  legendeBox: {
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 4,
    padding: 6,
    marginBottom: 4,
    marginTop: 8,
    backgroundColor: "#fafafa",
    width: "100%",
  },
  legendeTitre: {
    fontSize: 9,
    fontWeight: "bold",
    color: COULEURS_RESULTAT_PDF.noir,
    marginBottom: 4,
  },
  legendeTexte: {
    fontSize: 8,
    lineHeight: 1.35,
    color: COULEURS_RESULTAT_PDF.gris,
    marginBottom: 2,
  },
  legendeLabel: {
    fontWeight: "bold",
    color: COULEURS_RESULTAT_PDF.noir,
  },
  blocExamen: {
    marginBottom: 8,
    marginTop: 2,
  },
});
